name: WordPress WPScan

on:
  push:
    branches:
      - main

jobs:
  wpscan:
    runs-on: ubuntu-latest
    env:
      DB_PASSWORD: ${{ secrets.Fofiu_Florin_George_DB_PASS }}
      MYSQL_ROOT_PASSWORD: ${{ secrets.Fofiu_Florin_George_DB_PASS }}

      # pull WP admin creds from your new secrets:
      WP_ADMIN_USER: ${{ secrets.Fofiu_Florin_George_WP_ADMIN_USER }}
      WP_ADMIN_PASSWORD: ${{ secrets.Fofiu_Florin_George_WP_ADMIN_PASSWORD }}
      WP_ADMIN_EMAIL: ${{ secrets.FOFIU_FLORIN_GEORGE_WP_ADMIN_EMAIL }}

      WPSCAN_API_TOKEN: ${{ secrets.Fofiu_Florin_George_WPSCAN_API_TOKEN }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Start WordPress stack and wait for HTTP 200
        run: |
          docker-compose up -d
          echo "Waiting for WP…"
          for i in {1..30}; do
            if curl -sSf http://localhost:8080 >/dev/null; then
              echo "✔️ WordPress is up"
              break
            fi
            echo "→ retry $i/30…"
            sleep 5
          done
          if ! curl -sSf http://localhost:8080 >/dev/null; then
            echo "❌ WP never became available."
            exit 1
          fi

      - name: Install WordPress via WP-CLI
        run: |
          WP_CONTAINER=$(docker-compose ps -q wordpress)
          docker exec $WP_CONTAINER wp core install \
            --url="http://localhost:8080" \
            --title="Test Site" \
            --admin_user="${WP_ADMIN_USER}" \
            --admin_password="${WP_ADMIN_PASSWORD}" \
            --admin_email="${WP_ADMIN_EMAIL}"
          echo "✔️ WP installed (admin:'${WP_ADMIN_USER}')"

      - name: Run WPScan
        run: |
          docker run --rm --network host \
            -e WPSCAN_API_TOKEN="${WPSCAN_API_TOKEN}" \
            wpscanteam/wpscan \
              --url http://localhost:8080 \
              --api-token "${WPSCAN_API_TOKEN}" \
              --enumerate ap,at,cb,dbe,u \
              --disable-tls-checks

      - name: Tear down
        if: ${{ always() }}
        run: docker-compose down
